/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_proyecto;

import Clases.Global;
import Clases.Matriz;
import Clases.Palabra;
import interfaz_proyecto.Ventana3;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyecto1.Listas.ListaSimplementeEnlazada;


/**
 *
 * @author salom
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        Ventana1 v1 = new Ventana1();
        this.setLocationRelativeTo(null);      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cargar_archivo = new javax.swing.JPanel();
        Cargar_Archivo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor seleccione el archivo que será utilizado ");

        Cargar_archivo.setBackground(new java.awt.Color(102, 153, 255));

        Cargar_Archivo.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        Cargar_Archivo.setForeground(new java.awt.Color(255, 255, 255));
        Cargar_Archivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cargar_Archivo.setText("CARGAR ARCHIVO");
        Cargar_Archivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Cargar_Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cargar_Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cargar_ArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cargar_archivoLayout = new javax.swing.GroupLayout(Cargar_archivo);
        Cargar_archivo.setLayout(Cargar_archivoLayout);
        Cargar_archivoLayout.setHorizontalGroup(
            Cargar_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(Cargar_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cargar_archivoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Cargar_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Cargar_archivoLayout.setVerticalGroup(
            Cargar_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(Cargar_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cargar_archivoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Cargar_Archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("en la ejecución de este programa.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cargar_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Cargar_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        continuar.setBackground(new java.awt.Color(102, 153, 255));
        continuar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        continuar.setForeground(new java.awt.Color(255, 255, 255));
        continuar.setText("continuar");
        continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarMouseClicked(evt);
            }
        });
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CARGAR ARCHIVO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(continuar)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continuar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cargar archivos del sistema mediante JFileChooser
     * @param evt 
     */
    private void Cargar_ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cargar_ArchivoMouseClicked
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".txt", "txt");
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int result = file.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            Global.setFile(file.getSelectedFile());
            JOptionPane.showMessageDialog(null, "Su archivo ha sido creado con exito");
        }
    }//GEN-LAST:event_Cargar_ArchivoMouseClicked
    
    /**
     * valida que file este vacio
     * @return 
     */
    private boolean FileIsEmpty(){
        return Global.getFile() == null;
    }
    
    
    /**
     * Boton que muestra la siguiente ventana de la interfaz
     * @param evt 
     */
    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        if(FileIsEmpty()){
            //Se muestra una alerta en caso de no haber seleccionado el archivo 
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun archivo");
        }else{
                String path = Global.getFile().getAbsolutePath();
                ListaSimplementeEnlazada<Palabra> ListaDiccionario = 
                        new ListaSimplementeEnlazada<>(100);
                //
                ListaSimplementeEnlazada<Character> ListaLetras = 
                        new ListaSimplementeEnlazada<>(100);
                try {
                    // se crea un objeto buffered reader para leer el txt
                    BufferedReader br = new BufferedReader(new FileReader(path));
                    String linea;
                    // variables booleanas para confirmación dentro de la lectura
                    boolean ReadingDictionary = false;
                    boolean ReadingBoard = false;
                    // leer la linea 
                    linea = br.readLine();
                    //Se lee cada linea del archivo y al momento en el que se encuentra
                    //con alguna etiqueta cambia el valor de las variables booleanas
                    // y asi poder identificar si se está o no leyendo.
                    while ((linea = br.readLine()) != null) {
                        //diccionario
                        if (linea.trim().equals("dic")){
                            ReadingDictionary = true;
                            continue;
                        }
                        if (linea.trim().equals("/dic")){
                            ReadingDictionary = false;
                            continue;
                        }
                        if (ReadingDictionary){
                            // Creamos un objeto palabra
                            Palabra palabra = new Palabra(linea);
                            //System.out.println("Linea" + linea);
                            System.out.println("Objeto" + palabra.getPalabra());
                            // Agregamos la palabra a la lista de forma ordenada
                            ListaDiccionario.addAtEnd(palabra);
                            
                            //Tablero
                        }
                        if (linea.trim().equals("tab")){
                            ReadingBoard = true;
                            continue;
                        }
                        if (linea.trim().equals("/tab")){
                            ReadingBoard = false;
                            continue;
                            // Agregar las filas al tablero
                        }
                        if (ReadingBoard){
                            String[] caracteres = linea.split(",");
                            for (String caracter : caracteres){
                                System.out.println("Linea" + caracter);
                                ListaLetras.addAtEnd(caracter.charAt(0));
                                //ListaLetras.print();
                            }
                        }
                    }
                    Global.setListaLetras(ListaLetras);
                    Global.setListaPalabras(ListaDiccionario);
                    // Se cierra el objeto Buffered
                    br.close();
                
                    //System.out.println("PALABRAS");
                    //Global.getListaLetras().print();
                    //System.out.println("TABLERO");
                    //Global.getListaLetras().print();
                //if (Global.getListaPalabras().isEmpty()){
                    //JOptionPane.showMessageDialog(null,"No se pudo guardar el diccionario");
                //} else if(Global.getListaLetras().isEmpty()){
                    //JOptionPane.showMessageDialog(null, "El tablero está vacío");
                //}else{
                    Ventana3 v3 = new Ventana3();
                    v3.setLocationRelativeTo(null);
                    v3.setVisible(true);
                    this.dispose();  
                //}
                
                } catch(IOException e){
                    JOptionPane.showMessageDialog(null, "Error al leer el archivo:" + e.getMessage());
                }    
            }
    }//GEN-LAST:event_continuarActionPerformed

    private void continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarMouseClicked
        
    }//GEN-LAST:event_continuarMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cargar_Archivo;
    private javax.swing.JPanel Cargar_archivo;
    private javax.swing.JButton continuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
